/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'Food' : null } |
  { 'Recreational' : null } |
  { 'Utility' : null };
export type Timestamp = bigint;
export interface Transaction {
  'id' : bigint,
  'description' : string,
  'timestamp' : bigint,
  'category' : Category,
  'amount' : number,
}
export interface WeekRecord {
  'recTotal' : number,
  'endDate' : bigint,
  'utilTotal' : number,
  'grandTotal' : number,
  'foodTotal' : number,
  'startDate' : bigint,
  'weekId' : bigint,
}
export interface WeekSummary {
  'recTotal' : number,
  'endDate' : bigint,
  'utilTotal' : number,
  'grandTotal' : number,
  'foodTotal' : number,
  'startDate' : bigint,
  'weekId' : bigint,
}
export interface _SERVICE {
  'addTransaction' : ActorMethod<[number, string, Category], Transaction>,
  'checkAndResetWeek' : ActorMethod<[], boolean>,
  'deleteTransaction' : ActorMethod<[bigint], boolean>,
  'getCurrentWeekSummary' : ActorMethod<[], WeekSummary>,
  'getCurrentWeekTransactions' : ActorMethod<[], Array<Transaction>>,
  'getExportData' : ActorMethod<
    [],
    Array<[Timestamp, number, Category, string]>
  >,
  'getSpendingLimit' : ActorMethod<[], [] | [number]>,
  'getTodayTransactions' : ActorMethod<[], Array<Transaction>>,
  'getWeekHistory' : ActorMethod<[], Array<WeekRecord>>,
  'getWeekTransactions' : ActorMethod<[bigint], Array<Transaction>>,
  'setSpendingLimit' : ActorMethod<[number], undefined>,
  'updateTransaction' : ActorMethod<
    [bigint, number, string, Category],
    [] | [Transaction]
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];