/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'Food' : IDL.Null,
  'Recreational' : IDL.Null,
  'Utility' : IDL.Null,
});
export const Transaction = IDL.Record({
  'id' : IDL.Nat,
  'description' : IDL.Text,
  'timestamp' : IDL.Int,
  'category' : Category,
  'amount' : IDL.Float64,
});
export const WeekSummary = IDL.Record({
  'recTotal' : IDL.Float64,
  'endDate' : IDL.Int,
  'utilTotal' : IDL.Float64,
  'grandTotal' : IDL.Float64,
  'foodTotal' : IDL.Float64,
  'startDate' : IDL.Int,
  'weekId' : IDL.Nat,
});
export const Timestamp = IDL.Int;
export const WeekRecord = IDL.Record({
  'recTotal' : IDL.Float64,
  'endDate' : IDL.Int,
  'utilTotal' : IDL.Float64,
  'grandTotal' : IDL.Float64,
  'foodTotal' : IDL.Float64,
  'startDate' : IDL.Int,
  'weekId' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addTransaction' : IDL.Func(
      [IDL.Float64, IDL.Text, Category],
      [Transaction],
      [],
    ),
  'checkAndResetWeek' : IDL.Func([], [IDL.Bool], []),
  'deleteTransaction' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getCurrentWeekSummary' : IDL.Func([], [WeekSummary], ['query']),
  'getCurrentWeekTransactions' : IDL.Func(
      [],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'getExportData' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(Timestamp, IDL.Float64, Category, IDL.Text))],
      ['query'],
    ),
  'getSpendingLimit' : IDL.Func([], [IDL.Opt(IDL.Float64)], ['query']),
  'getTodayTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getWeekHistory' : IDL.Func([], [IDL.Vec(WeekRecord)], ['query']),
  'getWeekTransactions' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Transaction)],
      ['query'],
    ),
  'setSpendingLimit' : IDL.Func([IDL.Float64], [], []),
  'updateTransaction' : IDL.Func(
      [IDL.Nat, IDL.Float64, IDL.Text, Category],
      [IDL.Opt(Transaction)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'Food' : IDL.Null,
    'Recreational' : IDL.Null,
    'Utility' : IDL.Null,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Nat,
    'description' : IDL.Text,
    'timestamp' : IDL.Int,
    'category' : Category,
    'amount' : IDL.Float64,
  });
  const WeekSummary = IDL.Record({
    'recTotal' : IDL.Float64,
    'endDate' : IDL.Int,
    'utilTotal' : IDL.Float64,
    'grandTotal' : IDL.Float64,
    'foodTotal' : IDL.Float64,
    'startDate' : IDL.Int,
    'weekId' : IDL.Nat,
  });
  const Timestamp = IDL.Int;
  const WeekRecord = IDL.Record({
    'recTotal' : IDL.Float64,
    'endDate' : IDL.Int,
    'utilTotal' : IDL.Float64,
    'grandTotal' : IDL.Float64,
    'foodTotal' : IDL.Float64,
    'startDate' : IDL.Int,
    'weekId' : IDL.Nat,
  });
  
  return IDL.Service({
    'addTransaction' : IDL.Func(
        [IDL.Float64, IDL.Text, Category],
        [Transaction],
        [],
      ),
    'checkAndResetWeek' : IDL.Func([], [IDL.Bool], []),
    'deleteTransaction' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getCurrentWeekSummary' : IDL.Func([], [WeekSummary], ['query']),
    'getCurrentWeekTransactions' : IDL.Func(
        [],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getExportData' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(Timestamp, IDL.Float64, Category, IDL.Text))],
        ['query'],
      ),
    'getSpendingLimit' : IDL.Func([], [IDL.Opt(IDL.Float64)], ['query']),
    'getTodayTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getWeekHistory' : IDL.Func([], [IDL.Vec(WeekRecord)], ['query']),
    'getWeekTransactions' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'setSpendingLimit' : IDL.Func([IDL.Float64], [], []),
    'updateTransaction' : IDL.Func(
        [IDL.Nat, IDL.Float64, IDL.Text, Category],
        [IDL.Opt(Transaction)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };