/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface WeekRecord {
    recTotal: number;
    endDate: bigint;
    utilTotal: number;
    grandTotal: number;
    foodTotal: number;
    startDate: bigint;
    weekId: bigint;
}
export interface WeekSummary {
    recTotal: number;
    endDate: bigint;
    utilTotal: number;
    grandTotal: number;
    foodTotal: number;
    startDate: bigint;
    weekId: bigint;
}
export interface Transaction {
    id: bigint;
    description: string;
    timestamp: bigint;
    category: Category;
    amount: number;
}
export enum Category {
    Food = "Food",
    Recreational = "Recreational",
    Utility = "Utility"
}
export interface backendInterface {
    addTransaction(amount: number, description: string, category: Category): Promise<Transaction>;
    checkAndResetWeek(): Promise<boolean>;
    deleteTransaction(id: bigint): Promise<boolean>;
    getCurrentWeekSummary(): Promise<WeekSummary>;
    getCurrentWeekTransactions(): Promise<Array<Transaction>>;
    getExportData(): Promise<Array<[Timestamp, number, Category, string]>>;
    getSpendingLimit(): Promise<number | null>;
    getTodayTransactions(): Promise<Array<Transaction>>;
    getWeekHistory(): Promise<Array<WeekRecord>>;
    getWeekTransactions(weekId: bigint): Promise<Array<Transaction>>;
    setSpendingLimit(limit: number): Promise<void>;
    updateTransaction(id: bigint, amount: number, description: string, category: Category): Promise<Transaction | null>;
}
import type { Category as _Category, Timestamp as _Timestamp, Transaction as _Transaction } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addTransaction(arg0: number, arg1: string, arg2: Category): Promise<Transaction> {
        if (this.processError) {
            try {
                const result = await this.actor.addTransaction(arg0, arg1, to_candid_Category_n1(this._uploadFile, this._downloadFile, arg2));
                return from_candid_Transaction_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTransaction(arg0, arg1, to_candid_Category_n1(this._uploadFile, this._downloadFile, arg2));
            return from_candid_Transaction_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async checkAndResetWeek(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.checkAndResetWeek();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkAndResetWeek();
            return result;
        }
    }
    async deleteTransaction(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTransaction(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTransaction(arg0);
            return result;
        }
    }
    async getCurrentWeekSummary(): Promise<WeekSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentWeekSummary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentWeekSummary();
            return result;
        }
    }
    async getCurrentWeekTransactions(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentWeekTransactions();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentWeekTransactions();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExportData(): Promise<Array<[Timestamp, number, Category, string]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExportData();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExportData();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSpendingLimit(): Promise<number | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSpendingLimit();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSpendingLimit();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTodayTransactions(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTodayTransactions();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTodayTransactions();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWeekHistory(): Promise<Array<WeekRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWeekHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWeekHistory();
            return result;
        }
    }
    async getWeekTransactions(arg0: bigint): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWeekTransactions(arg0);
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWeekTransactions(arg0);
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async setSpendingLimit(arg0: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setSpendingLimit(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setSpendingLimit(arg0);
            return result;
        }
    }
    async updateTransaction(arg0: bigint, arg1: number, arg2: string, arg3: Category): Promise<Transaction | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTransaction(arg0, arg1, arg2, to_candid_Category_n1(this._uploadFile, this._downloadFile, arg3));
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTransaction(arg0, arg1, arg2, to_candid_Category_n1(this._uploadFile, this._downloadFile, arg3));
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Category_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Transaction_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transaction): Transaction {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Transaction]): Transaction | null {
    return value.length === 0 ? null : from_candid_Transaction_n3(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    description: string;
    timestamp: bigint;
    category: _Category;
    amount: number;
}): {
    id: bigint;
    description: string;
    timestamp: bigint;
    category: Category;
    amount: number;
} {
    return {
        id: value.id,
        description: value.description,
        timestamp: value.timestamp,
        category: from_candid_Category_n5(_uploadFile, _downloadFile, value.category),
        amount: value.amount
    };
}
function from_candid_tuple_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_Timestamp, number, _Category, string]): [Timestamp, number, Category, string] {
    return [
        value[0],
        value[1],
        from_candid_Category_n5(_uploadFile, _downloadFile, value[2]),
        value[3]
    ];
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Food: null;
} | {
    Recreational: null;
} | {
    Utility: null;
}): Category {
    return "Food" in value ? Category.Food : "Recreational" in value ? Category.Recreational : "Utility" in value ? Category.Utility : value;
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transaction>): Array<Transaction> {
    return value.map((x)=>from_candid_Transaction_n3(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_Timestamp, number, _Category, string]>): Array<[Timestamp, number, Category, string]> {
    return value.map((x)=>from_candid_tuple_n9(_uploadFile, _downloadFile, x));
}
function to_candid_Category_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    Food: null;
} | {
    Recreational: null;
} | {
    Utility: null;
} {
    return value == Category.Food ? {
        Food: null
    } : value == Category.Recreational ? {
        Recreational: null
    } : value == Category.Utility ? {
        Utility: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
